# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  #
  ## TARGET 1
  # 
	config.vm.define "target1" do |target1|
    # Image
    target1.vm.box = "ubuntu/jammy64"

    # Network settings
	  target1.vm.hostname = "target1"
	  target1.vm.define "target1"
    target1.vm.network "public_network", :bridge => "enp3s0", ip: "192.168.2.250", hostname: true
	  target1.vm.synced_folder ".", "/vagrant"

    # Simulated hardware
	  target1.vm.provider "virtualbox" do |v|
	    v.memory = 1024
	    v.cpus = 2
    end

    # Provision box
	  target1.vm.provision "shell", inline: <<-SHELL
	  ls /vagrant
	  cd /vagrant/target1
	  chmod +x bootstrap.sh
	  sudo ./bootstrap.sh
	  SHELL
	end

  #
  ## TARGET 2
  # 
	config.vm.define "target2" do |target2|
    # Image
    target2.vm.box = "ubuntu/jammy64"

    # Network settings
	  target2.vm.hostname = "target2"
	  target2.vm.define "target2"
    target2.vm.network "public_network", :bridge => "enp3s0", ip: "192.168.2.251", hostname: true
	  target2.vm.synced_folder ".", "/vagrant"

	  target2.vm.provider "virtualbox" do |v|
	    v.memory = 1024
	    v.cpus = 2
    end

    # Provision box
	  target2.vm.provision "shell", inline: <<-SHELL
	  ls /vagrant
	  cd /vagrant/target2
	  chmod +x bootstrap.sh
	  sudo ./bootstrap.sh
	  SHELL
	end
end
